# Multi-Container Stack Example
#
# Complex stack with:
# - PostgreSQL database
# - Redis cache
# - Sample web application
#
# All containers use:
# - restart: always (required for graceful shutdown)
# - Health checks for post-reboot verification
# - Named volumes for data persistence
#
# Usage:
#   docker-compose -f 02-multi-container.yml up -d
#
# Verify after reboot:
#   docker ps
#   docker-compose -f 02-multi-container.yml ps
#   curl http://localhost:8080/health

version: '3.8'

services:
  # Database
  postgres:
    image: postgres:16-alpine
    container_name: app-postgres
    restart: always  # CRITICAL: Use 'always' not 'unless-stopped'

    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: appdb

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      - app-network

  # Cache
  redis:
    image: redis:7-alpine
    container_name: app-redis
    restart: always

    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

    volumes:
      - redis_data:/data

    ports:
      - "6379:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

    networks:
      - app-network

  # Application
  app:
    image: nginx:alpine
    container_name: app-web
    restart: always

    volumes:
      - ./app-config.conf:/etc/nginx/conf.d/default.conf:ro
      - app_data:/usr/share/nginx/html

    ports:
      - "8080:80"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_data:
    driver: local

networks:
  app-network:
    driver: bridge
